apiVersion: v1
kind: Secret
metadata:
  name: enlightenlm-secrets
  namespace: default
type: Opaque
data:
  deepseek_api_key: "c29tZV9kZWVwcy1rZXk="  # base64 encoded
  ollama_api_key: "c29tZV9vbGxhbWFfa2V5="  # base64 encoded